spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: consumer-rocketmq

server:
  # 随机端口  方便启动多个消费者  9293
  port: ${random.int[10000,19999]}