feign:
  httpclient:
    enabled: true
  client:
    config:
      # 全局配置
      default:
        connect-timeout: 3000
        read-timeout: 60000
      # 局部配置
      provider-nacos-discovery:
        connect-timeout: 30000
        read-timeout: 60000
  compression:
    request:
      enabled: true
    response:
      enabled: true