spring:
  application:
    name: consumer-depart
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 124.221.56.164:8848
        username: nacos
        password: meet_nacos
        namespace: 4ad4c584-3999-4cae-9adc-bfaca2a00f0a
        group: MEET-GROUP
        file-extension: yaml
  config:
    # nacos dataId名字consumer-depart-dev.yaml
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}

feign:
  httpclient:
    enabled: true
  client:
    config:
      # 全局配置
      default:
        connect-timeout: 3000
        read-timeout: 60000
      # 局部配置
      provider-depart:
        connect-timeout: 30000
        read-timeout: 60000
  compression:
    request:
      enabled: true
    response:
      enabled: true