### 以下配置存入nacos

spring:
  application:
    # 微服务命名不能有下划线！！！  否则restTemplate调用识别不到
    name: consumer-depart
  cloud:
    nacos:
      discovery:
        server-addr: 124.221.56.164:8848
        username: nacos
        password: meet_nacos
        namespace: 4ad4c584-3999-4cae-9adc-bfaca2a00f0a
        group: MEET-GROUP