spring:
  cloud:
    nacos:
      # nacos作为注册中心配置项
      discovery:
        server-addr: 124.221.56.164:8848
        # 注册到nacos的服务名  默认值为spring.application.name
        service: ${spring.application.name}
        # sit环境namespace id
        namespace: 5dda1a11-b00c-42b7-a19a-0290cc1218b5