server:
  port: 9000

logging:
  level:
    com.you.meet.cloud.*: debug
  config: classpath:logback.xml


spring:
  application:
    name: gateway-test
  cloud:
    nacos:
      discovery:
        server-addr: 124.221.56.164:8848
        username: nacos
        password: meet_nacos
        namespace: 4ad4c584-3999-4cae-9adc-bfaca2a00f0a
        group: MEET-GROUP
  profiles:
    active: cors