spring:
  application:
    name: provider-depart
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 124.221.56.164:8848
        username: nacos
        password: meet_nacos
        namespace: 4ad4c584-3999-4cae-9adc-bfaca2a00f0a
        group: MEET-GROUP
        file-extension: yaml
  config:
    # nacos dataId名字provider-depart-dev.yaml
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}