server:
  port: 8081

spring:
  datasource:
    test:
      url: jdbc:mysql://124.221.56.164:3306/test?useSSL=false&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useUnicode=true&autoReconnect=true&failOverReadOnly=false&useAffectedRows=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      # 指定为HikariDataSource
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        pool-name: HikariCP-provider_8081
        #最小空闲连接数
        minimum-idle: 5
        # 空闲连接存活最大时间，默认10分钟
        idle-timeout: 240000
        # 连接池最大连接数，默认是10
        maximum-pool-size: 10
        # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
        auto-commit: true
        # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
        max-lifetime: 300000
        # 数据库连接超时时间,默认30秒
        connection-timeout: 10000
        # 连接测试query
        connection-test-query: SELECT 1
  application:
    # 微服务命名不能有下划线！！！  否则restTemplate调用识别不到
    name: provider-depart
  cloud:
    nacos:
      discovery:
        # 集群逗号分隔
        server-addr: 124.221.56.164:8848
        username: nacos
        password: meet_nacos
        # 数据隔离  命名空间-group-微服务
        namespace: 4ad4c584-3999-4cae-9adc-bfaca2a00f0a
        group: MEET-GROUP

logging:
  level:
    com.you.meet.nice.*: debug
  config: classpath:logback.xml
