server:
  port: 8090
spring:
  profiles:
    #active: local
    active: hp
  application:
    name: consumer
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

management:
  endpoints:
    web:
      exposure:
        include: '*'