spring:
  cloud:
    nacos:
      # nacos作为注册中心配置项
      discovery:
        server-addr: 124.221.56.164:8848
        # 注册到nacos的服务名  默认值为spring.application.name
        service: ${spring.application.name}
        # dev环境namespace id
        namespace: 4ad4c584-3999-4cae-9adc-bfaca2a00f0a
    # Sentinel 配置项，对应 SentinelProperties 配置属性类
    sentinel:
      enabled: true
      # 设置是否饥饿加载，默认为 false 关闭。默认情况下，Sentinel 是延迟初始化，在首次使用到 Sentinel 才进行初始化。通过设置为 true 时，在项目启动时就会将 Sentinel 直接初始化，完成向 Sentinel 控制台进行注册。
      eager: true
      transport:
        dashboard: 192.168.56.10:8858
      # 设置拦截请求的地址
      filter:
        url-patterns: /**
      # Sentinel 规则的数据源，是一个 Map 类型。key 为数据源名，可自定义；value 为数据源的具体配置
      datasource:
        ds1:
          nacos:
            server-addr: 124.221.56.164:8848 # Nacos 服务器地址
            namespace: 4ad4c584-3999-4cae-9adc-bfaca2a00f0a  # Nacos 命名空间
            data-id: ${spring.application.name}-flow-rule # Nacos 配置集编号
            data-type: json # 数据格式
            rule-type: FLOW # 规则类型
    # Spring Cloud Stream 配置项，对应 BindingServiceProperties 类
    stream:
      # Binding 配置项，对应 BindingProperties 是个Map
      bindings:
        demo01-output:
          # 目的地。这里使用 RocketMQ Topic
          destination: DEMO-TOPIC-01
          # 内容格式。这里使用 JSON
          content-type: application/json
      # Spring Cloud Stream RocketMQ 配置项
      rocketmq:
        # RocketMQ Binder 配置项，对应 RocketMQBinderConfigurationProperties 类
        binder:
          # RocketMQ Namesrv 地址
          name-server: 192.168.56.10:9876;192.168.56.10:9877
        # RocketMQ 自定义 Binding 配置项，对应 RocketMQBindingProperties Map
        bindings:
          demo01-output:
            # RocketMQ Producer 配置项，对应 RocketMQProducerProperties 类
            producer:
              # 同一类 Producer 的集合，这类 Producer 发送同一类消息且发送逻辑一致。如果发送的是事务消息且原始生产者在发送之后崩溃，则 Broker 服务器会联系同一生产者组的其他生产者实例以提交或回溯消费。
              group: demo01-provider-group-DEMO-TOPIC-01
              # 是否同步发送消息，默认为 false 异步。
              sync: true
























