spring:
  cloud:
    nacos:
      discovery:
        server-addr: 124.221.56.164:8848
        namespace: 4ad4c584-3999-4cae-9adc-bfaca2a00f0a
    # Sentinel 配置项，对应 SentinelProperties 配置属性类
    sentinel:
      enabled: true
      # 设置是否饥饿加载，默认为 false 关闭。默认情况下，Sentinel 是延迟初始化，在首次使用到 Sentinel 才进行初始化。通过设置为 true 时，在项目启动时就会将 Sentinel 直接初始化，完成向 Sentinel 控制台进行注册。
      eager: true
      transport:
        dashboard: 192.168.56.10:8858
      # 设置拦截请求的地址
      filter:
        url-patterns: /**

    # Spring Cloud Stream 配置项，对应 BindingServiceProperties 类
    stream:
      # Binding 配置项，对应 BindingProperties 是个Map
      bindings:
        demo01-input:
          # 目的地。这里使用 RocketMQ Topic
          destination: DEMO-TOPIC-01
          # 内容格式。这里使用 JSON
          content-type: application/json
          # 消费者分组
          group: x-demo01-consumer-group-DEMO-TOPIC-01
      # Spring Cloud Stream RocketMQ 配置项
      rocketmq:
        # RocketMQ Binder 配置项，对应 RocketMQBinderConfigurationProperties 类
        binder:
          # RocketMQ Namesrv 地址
          name-server: 192.168.56.10:9876;192.168.56.10:9877
        # RocketMQ 自定义 Binding 配置项，对应 RocketMQBindingProperties Map
        bindings:
          demo01-input:
            # RocketMQ Producer 配置项，对应 RocketMQProducerProperties 类
            consumer:
              # 是否开启消费，默认为 true
              enabled: true
              # 是否使用广播消费，默认为 false 使用集群消费
              broadcasting: false

feign:
  sentinel:
    # 开启 Sentinel 对 Feign 的支持，默认为 false 关闭。
    enabled: true