spring:
  cloud:
    gateway:
      routes:
        - id: filterdefault_route1
          uri: http://localhost:8980
          predicates:
            - Path=/a/**

        - id: filterdefault_route2
          uri: http://localhost:8980
          predicates:
            - Path=/b/**
      default-filters:
        # 降级策略   和全局异常处理器不能同时存在
        - name: CircuitBreaker
          args:
            name: myCircuitBreaker
            fallbackUri: forward:/fb