server:
  port: 8080
spring:
  profiles:
    #active: local
    active: hp
  application:
    name: memcache
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss