server:
  port: 8080
  servlet:
    context-path: /memcache
spring:
  profiles:
    active: local
  application:
    name: memcache

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    banner: false