spring:
  profiles:
    active: demo01
  application:
    name: provider-kafka

server:
  port: 9191


# spring-kafka INFO 日志太多了，所以我们限制只打印 ERROR 级别  日志级别OFF>FATAL>ERROR>WARN>INFO>DEBUG>ALL
logging:
  level:
    org:
      springframework:
        kafka: ERROR
      apache:
        kafka: ERROR
