spring:
  # kafka配置项  对应KafkaProperties配置类
  kafka:
    # Kafka Broker集群地址
    bootstrap-servers:
      - localhost:19092
    # Kafka生产者配置
    producer:
      # 0-不应答。1-leader 应答。all-所有 leader 和 isr 应答。
      acks: all
      # 发送失败时，重试发送的次数
      retries: 3
      # 消息的 key 的序列化
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 消息的 value 的序列化
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 每次批量发送消息的最大数量  16K
      batch-size: 16384
      # 每次批量发送消息的最大内存 32M
      buffer-memory: 33554432
      properties:
        # 批处理延迟时间上限。这里配置为 30 * 1000 ms 过后，不管是否消息数量是否到达 batch-size 或者消息大小到达 buffer-memory 后，都直接发送一次请求。
        linger:
          ms: 30000