spring:
  # kafka配置项  对应KafkaProperties配置类
  kafka:
    # Kafka Broker集群地址
    bootstrap-servers:
      - localhost:19192
      - localhost:19292
      - localhost:19392
    # Kafka生产者配置
    producer:
      # 0-不应答。1-leader 应答。all-所有 leader 和 isr 应答。
      acks: all
      # 发送失败时，重试发送的次数
      retries: 3
      # 消息的 key 的序列化
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 消息的 value 的序列化
      value-serializer: org.apache.kafka.common.serialization.StringSerializer