POST http://localhost:8081/depart/save
Content-Type: application/json

{
  "name": "测试部门1111"
}

###
DELETE http://localhost:8081/depart/del/2

###
PUT http://localhost:8081/depart/update
Content-Type: application/json

{
  "id": 1,
  "name": "研发部门"
}

###
GET http://localhost:8081/depart/get/1

###
GET http://localhost:8081/depart/list