spring:
  profiles:
    active: demo07
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: consumer-kafka

server:
  port: ${random.int[10000,19999]}


# spring-kafka INFO 日志太多了，所以我们限制只打印 ERROR 级别  日志级别OFF>FATAL>ERROR>WARN>INFO>DEBUG>ALL
logging:
  level:
    org:
      springframework:
        kafka: ERROR
      apache:
        kafka: ERROR
