POST http://localhost:8080/depart/save
Content-Type: application/json

{
  "name": "运维部门"
}

###
DELETE http://localhost:8080/depart/del/2

###
PUT http://localhost:8080/depart/update
Content-Type: application/json

{
  "id": 1,
  "name": "研发部门"
}

###
GET http://localhost:8080/depart/get/1

###
GET http://localhost:8080/depart/list

###
GET http://localhost:8080/depart/discovery

###
GET http://localhost:8080/depart/instances